- name: Create a VPC in aws 
  ec2_vpc_net:
     name: Module_dev2
     cidr_block: 10.0.0.0/16
     region: us-east-1
     tags:
        module: ec2_vpc_net
        this: works
     tenancy: dedicated 
